export const moviesJSON = [
  {
    "title": "On the Silver Globe",
    "id": "on-the-silver-globe",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/35.jpg",
    "originalTitle": "NA SREBRNYM GLOBIE",
    "country": ["Poland"],
    "language": ["Polish"],
    "imdbRating": 7.3,
    "views": 0,
    "year": "1988",
    "genre": ["Adventure", "Fantasy"],
    "subs": ["EN", "PT", "RU"],
    "director": ["Andrzej Zulawski"],
    "actors": ["Andrzej Seweryn", "Grazyna Dylag", "Jerzy Trela"],
    "description": "is a Polish film premiered in 1988, directed by Andrzej Żuławski and adapted from a novel by Jerzy Żuławski.\n\nA small group of cosmic explorers leave Earth to find freedom and start a new civilization."
  },
  {
    "title": "Dekalog: One",
    "id": "dekalog-one",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/58.jpg",
    "originalTitle": "DEKALOG, JEDEN",
    "country": ["Poland"],
    "language": ["Polish"],
    "imdbRating": 9.1,
    "views": 0,
    "year": 1989,
    "genre": ["Drama", "TV Series"],
    "subs": ["AR", "EN", "PT", "RU"],
    "director": ["Krzysztof Kieslowski"],
    "actors": ["Henryk Baranowski", "Maja Komorowska", "Wojciech Klata"],
    "description": "is the first part of the television series Dekalog by Polish director Krzysztof Kieślowski, possibly connected to the first and second imperatives of the Ten Commandments: “I am the Lord your God; you shall have no other gods before me” and “Thou shalt not make unto thee any graven image.”\n\nA university professor (Henryk Baranowski) trains his young son in the use of reason and the scientific method, but is confronted with the unpredictability of fate. Reason is defied with tragic results."
  },
  {
    "title": "Time of the Gypsies",
    "id": "time-of-the-gypsies",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/89.jpg",
    "originalTitle": "DOM ZA VEŠANJE",
    "country": ["YUGOSLAVIA"],
    "language": ["Serbo-Croatian"],
    "imdbRating": 8.3,
    "views": 0,
    "year": 1988,
    "genre": ["Comedy", "Crime Movies", "Drama"],
    "subs": ["NL", "EN", "ES", "TR"],
    "director": ["Emir Kusturica"],
    "actors": ["Bora Todorovic"],
    "description": "is a 1988 Yugoslavian film, directed by Emir Kusturica.\n\nIn this luminous tale set in the former Yugoslavia, Perhan, an engaging young Romany with telekinetic powers, is seduced by the quick-cash world of petty crime that threatens to destroy him and those he loves."
  },
  {
    "title": "A Love in Germany",
    "id": "a-love-in-germany",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/206.jpg",
    "originalTitle": "EINE LIEBE IN DEUTSCHLAND",
    "country": ["Germany"],
    "language": ["German"],
    "imdbRating": 6.8,
    "views": 0,
    "year": 1983,
    "genre": ["Drama", "Erotic Movies"],
    "subs": ["EN", "FR", "ES"],
    "director": ["Andrzej Wajda"],
    "actors": ["Armin Mueller-Stahl", "Hanna Schygulla", "Piotr Lysak"],
    "description": "is a 1983 feature film directed by Andrzej Wajda.\n\nThe film is based on the novel by Rolf Hochhuth about a woman who commits adultery with a prisoner of war while her husband serves as a soldier during World War II. A Love in Germany, featuring many popular German actors, was produced by German film producer Artur Brauner and German broadcaster ZDF.\n\nIn May of 1983, a man turns 49 and, with his 17-year old son, journeys to the village in Baden that he left 40 years before. He wants to discover what happened then, the truth about an affair his mother had with a young Polish prisoner of war, how the authorities came to learn of it, the lovers’ arrest, and the aftermath. While his son takes Polaroid photographs, he retraces the steps of his childhood and interviews those who should remember. The story is disclosed in flashbacks that focus on the lovers (Paulina and Stanislaus), on a jealous and conniving neighbor, and on Mayer, the local SS commander who wants to find a way out of inevitable consequences."
  },
  {
    "title": "When Father Was Away on Business",
    "id": "when-father-was-away-on-business",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/88.jpg",
    "originalTitle": "OTAC NA SLUŽBENOM PUTU",
    "country": ["YUGOSLAVIA"],
    "language": ["Serbo-Croatian"],
    "imdbRating": 7.9,
    "views": 0,
    "year": 1985,
    "genre": ["Drama"],
    "subs": ["CS", "EN", "FR", "HE", "PT", "RO", "RU", "ES", "TR"],
    "director": ["Emir Kusturica"],
    "actors": ["Mirjana Karanovic"],
    "description": "is a 1985 Yugoslav film by director Emir Kusturica. The screenplay was written by the Bosnian dramatist Abdulah Sidran. Its subtitle is A Historical Love Film and it was produced by Centar Film and Forum, production companies based in Sarajevo.\n\nSet in post-World War II Yugoslavia during the Informbiro period, the film tells the story from the perspective of a boy, Malik, whose father Meša (Miki Manojlović) was sent to a labour camp. When Father Was Away on Business won the Palme d’Or at the 1985 Cannes Film Festival and was nominated for the Academy Award for Best Foreign Language Film."
  },
  {
    "title": "Armourless Knight",
    "id": "armourless-knight",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/588.jpg",
    "originalTitle": "РИЦАР БЕЗ БРОНЯ",
    "country": ["Bulgaria"],
    "language": ["Bulgarian"],
    "imdbRating": 7.8,
    "views": 0,
    "year": 1966,
    "genre": ["Drama", "Family Movies"],
    "subs": ["EN", "RU"],
    "director": ["Borislav Sharaliev"],
    "actors": ["Apostol Karamitev", "Mariya Rusalieva", "Oleg Kovachev", "Oleg Popov", "Tania Massalitinova", "Tzvyatko Nikolov"],
    "description": "is a 1966 Bulgarian film directed by Borislav Sharaliev.\n\nImpersonating a knight is one of the favorite games of nine-year-old protagonist. Now as Don Quixote, now as D’Artagnan he is fighting evil, he is searching for justice and defending the weak. Together with his friends, packed in cardboard armor, they play all day long. As he is playing, however, he unwittingly witnesses the relation between his parents and gradually comes to understand that the world of the adults is far removed from the canons of knightly honor. His parents love him, but never seem to find the time to listen to his concerns. The deceit, corruption and lack of respect in his own family alienate the small boy. The only adult, whom the boy trusts, is his uncle to whom he is attached by a genuine, equal, man-to-man friendship. He takes him to the cinema and theater performances and talks to him like with his peer. Will this sensitive kid ever succeed in building an internal armor against selfishness and rudeness?"
  },
  {
    "title": "Celebration in the Botanical Garden",
    "id": "celebration-in-the-botanical-garden",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/586-2.jpg",
    "originalTitle": "SLÁVNOST V BOTANICKEJ ZÁHRADE",
    "country": ["Czechoslovakia"],
    "language": ["Slovak"],
    "imdbRating": 6.5,
    "views": 0,
    "year": 1969,
    "genre": ["Adventure", "Comedy", "Fantasy"],
    "subs": ["EN", "SK"],
    "director": ["Elo Havetta"],
    "actors": ["Dusan Blaskovic", "Jirí Sýkora", "Nina Divísková", "Slavoj Urban", "Sylvia Turbová"],
    "description": "is a 1969 Czechoslovak film directed by Elo Havetta.\n\nOne of the lead characters is Maria, an inn keeper; always a bride but never a wife. She meets the newcomer Pierre, who disturbs the peace of the small village and teaches the locals how to enjoy life. The film is full of fireworks of lovely colours, and a warm feeling. It is like a carousel of humour and human situations that carry us away, from the very first frame to the unexpected ending, making the viewer laugh gaily. Using a mosaic approach to the traditional narrative line, the film director creates a picture of fairly anarchic glee. “Celebration in the Botanical Garden” is a world of fantasy, full of summer fun, good humour and delight. E. Havetta´s debut was inspired by naïve art, French impressionism, and silent slap-stick as well as Western Slovakian folk traditions."
  },
  {
    "title": "Visions of Europe",
    "id": "visions-of-europe",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/412-1.jpg",
    "originalTitle": "VISIONS OF EUROPE",
    "country": ["Czechoslovakia", "Estonia", "Hungary", "Poland"],
    "language": ["German"],
    "imdbRating": 5.9,
    "views": 0,
    "year": 2004,
    "genre": ["Comedy", "Drama"],
    "subs": ["EN", "PT", "ES"],
    "director": ["Arvo Iho", "Béla Tarr", "Damjan Kozole", "Małgorzata Szumowska", "Martin Šulík", "Sasa Gedeon"],
    "actors": ["Abel Alves", "Johanna Troell", "Safia Aggoune"],
    "description": "is 2004 anthology film consisting of 25 short films by 25 different directors from Europe."
  },
  {
    "title": "The Notebook",
    "id": "the-notebook",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/546.jpg",
    "originalTitle": "A NAGY FÜZET",
    "country": ["Hungary"],
    "language": ["Hungarian"],
    "imdbRating": 7,
    "views": 0,
    "year": 2013,
    "genre": ["Drama", "War Movies"],
    "subs": ["ZH", "NL", "EN", "FR", "HE", "IT", "PT", "RO", "SK", "ES"],
    "director": ["János Szász"],
    "actors": ["András Gyémánt", "Diána Magdolna Kiss", "Gyöngyvér Bognár", "László Gyémánt", "Orsolya Tóth", "Péter Andorai", "Piroska Molnár", "Sabin Tambrea", "Ulrich Matthes", "Ulrich Thomsen"],
    "description": "is a 2013 Hungarian drama film directed by János Szász. It is based on the first novel, of the same name, of the 1986 prize winning trilogy by Ágota Kristóf.\n\nIn a village on the Hungarian border, two young brothers grow up during war time with their cruel grandmother and must learn every trick of evil to survive in the absurd world of adults."
  },
  {
    "title": "Three Days",
    "id": "three-days",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/425.jpg",
    "originalTitle": "TRYS DIENOS",
    "country": ["Lithuania"],
    "language": ["Russian"],
    "imdbRating": 7,
    "views": 0,
    "year": 1992,
    "genre": ["Drama"],
    "subs": ["EN"],
    "director": ["Šarūnas Bartas"],
    "actors": ["Arunas Sakalauskas", "Rimma Latypova", "Yekaterina Golubeva"],
    "description": "is a 1992 Lithuanian drama film directed by Šarūnas Bartas.\n\nIn Kaliningrad two Lithuanian boys meet two Russian girls. They have difficulties in finding places where they can sleep together. But this is the only problem they do solve. All four justly feel miserable because their lives are meaningless (the recurrent dull and poorly kept house façads could well be taken as a comparative symbol). In addition, everyone is so absorbed by his or her own distress and hardly capable of bothering about the anguish of the others. The three days end with a pervasive lack of contact. Written by Max Scharnberg, Stockholm."
  },
  {
    "title": "An Unforgettable Summer",
    "id": "an-unforgettable-summer",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/530.jpg",
    "originalTitle": "UN ÉTÉ INOUBLIABLE",
    "country": ["Romania"],
    "language": ["Romanian"],
    "imdbRating": 7.3,
    "views": 0,
    "year": 1994,
    "genre": ["Drama", "Romance", "War Movies"],
    "subs": ["EN", "RU", "ES", "TR"],
    "director": ["Lucian Pintilie"],
    "actors": ["Claudiu Bleont", "Kristin Scott Thomas"],
    "description": "is a 1994 Romanian drama film directed and produced by Lucian Pintilie.\n\nIn 1925 Romania, young Marie-Therese Von Debretsy refuses the flirtatious advances of her husband’s commanding officer. As a result, the cosmopolitan family is reassigned to a brutally bleak and dangerous outpost on the Bulgarian/Romanian frontier where both their relationship and humanity are severely tested."
  },
  {
    "title": "Andriesh",
    "id": "andriesh",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/578.jpg",
    "originalTitle": "АНДРИЕШ",
    "country": ["Ukraine"],
    "language": ["Russian"],
    "imdbRating": 6.3,
    "views": 0,
    "year": 1954,
    "genre": ["Drama", "Family Movies"],
    "subs": ["EN", "RU", "ES"],
    "director": ["Sergei Parajanov", "Yakov Bazelyan"],
    "actors": ["Domnika Dariyenko", "Giuli Chokhonelidze", "Konstantin Russu", "Ludmila Sokolova", "Nodar Shashigoglu", "Robert Klyavin"],
    "description": "is a 1954 Ukrainian SSR film directed by Yakov Bazelyan and Sergei Parajanov.\n\nAn adaptation of a fairy tale by Moldovan writer Emilian Bukov."
  },
  {
    "title": "Killer",
    "id": "killer",
    "image": "https://i0.wp.com/easterneuropeanmovies.com/wp-content/uploads/47.jpg",
    "originalTitle": "KILER",
    "country": ["Poland"],
    "language": ["Polish"],
    "imdbRating": 7.6,
    "views": 0,
    "year": 1997,
    "genre": ["Action Movies", "Comedy", "Crime Movies"],
    "subs": ["CS", "EN"],
    "director": ["Juliusz Machulski"],
    "actors": ["Cezary Pazura", "Jerzy Stuhr", "Malgorzata Kozuchowska"],
    "description": "is a 1997 Polish comedy by Juliusz Machulski, starring Cezary Pazura, Jerzy Stuhr, Janusz Rewiński, Jan Englert, Katarzyna Figura and Małgorzata Kożuchowska.\n\nAn innocent cab driver is mistaken for a contract killer and imprisoned. Soon, he is sprung by a mob boss who needs “Killer” for a few more jobs."
  }
]